# Generated by Django 5.1.3 on 2024-12-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0007_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("fortnightly", "Fortnightly")],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
