# Generated by Django 5.1.3 on 2024-12-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0009_remove_lessonschedule_location_studentrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorrequest",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("busy", "Busy")],
                default="available",
                max_length=20,
            ),
        ),
    ]
