# Generated by Django 5.1.4 on 2024-12-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_profile'),
        ('tutorials', '0010_tutorrequest_status'),
    ]

    operations = [
    ]
