# Generated by Django 4.2.16 on 2024-12-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_remove_student_completed_courses_and_more'),
        ('tutorials', '0012_alter_feedback_email_delete_profile'),
    ]

    operations = [
    ]
