# Generated by Django 5.1.3 on 2024-12-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequest",
            name="preferred_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
