# Generated by Django 5.1.4 on 2024-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_feedback_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrequest',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='available_time',
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='preferred_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='preferred_end_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='preferred_start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='available_end_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='available_end_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='available_start_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='available_start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paired', 'Paired')], default='pending', max_length=20),
        ),
    ]
