# Generated by Django 4.2.16 on 2024-12-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_student_completed_courses_student_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
    ]
