# Generated by Django 4.2.16 on 2024-12-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_merge_20241206_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrequest',
            old_name='subject',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='lessonschedule',
            name='end_time',
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='level_can_teach',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonschedule',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
